version: "3.8"
services:
  dev-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_DB: ${POSTGRES_BASE_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - test-net
networks:
  test-net: